version: '3.8'

services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: Dockerfile.server
    tty: true
    platform: linux/x86_64
    ports:
      - ${DB_PORT}:3306
    env_file:
      - ${ENV_FILE}
    volumes:
      - mysql_volume:/var/lib/mysql
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    container_name: ${API_CONTAINER_NAME}
    command: >
      /bin/sh -c "\
      dockerize -wait tcp://${DB_CONTAINER_NAME}:${DB_PORT} -timeout 90s && \
      npx prisma generate && \
      npx dotenv -e .env.develop prisma migrate dev && \
      yarn dev"
    build:
      context: ./
      dockerfile: Dockerfile.api
    tty: true
    ports:
      - ${API_PORT}:${CONTAINER_API_PORT}
    env_file:
      - ${ENV_FILE}
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /api/src
    networks:
      - backend

volumes:
  mysql_volume:
    name: ${VOLUME_NAME}

networks:
  backend:
    driver: bridge
